version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app/
    command: python manage.py run -h 0.0.0.0
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:14.0
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env.dev

volumes:
  pgdata:
